---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include kube-bench role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
