---
- name: Prepare
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Create the Kubernetes cluster with kind # noqa no-changed-when
      ansible.builtin.command: kind create cluster

    - name: Wait until all nodes are ready # noqa no-changed-when
      ansible.builtin.command: kubectl get nodes --no-headers
      register: kubectl_get_nodes
      until: kubectl_get_nodes.stdout_lines | select('match', '.*\\s+Ready\\s+.*') | list | length == kubectl_get_nodes.stdout_lines | length
      retries: 15
      delay: 10
